//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBd.WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        public int character_id { get; set; }
        public int user_id { get; set; }
        public string nickname { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> guild_id { get; set; }
    
        public virtual Guilds Guilds { get; set; }
        public virtual Users Users { get; set; }
    }
}
