//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBd.WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int log_id { get; set; }
        public int modified_user_id { get; set; }
        public string changed_text { get; set; }
        public System.DateTime change_date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
